### ISSUE TITLE
게시글Cell의 레이아웃 변경

### ISSUE THREAD

**Issue by zezer0** [CheeseInthe-Life/Daru-iOS#22]
## Description
PostCollectionViewCell,PostTableViewCell의 첨부사진 이미지뷰 추가 
Cell높이 고정으로 변경

## Todo
- [x] PostCollectionViewCell 이미지뷰 추가
- [x] PostTableViewCell 이미지뷰 추가
- [x] Cell 높이 고정으로 변경

**Comment by zezer0** [comment]
추가로 게시글 Cell의 높이를 고정높이로 변경
